# -*- coding: utf-8 -*-
"""simple _classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130GZSAoeiIeFqVeqiKkUHSvNbFdTSN0w
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import csv
import torch
import torch.nn as nn
from torch.utils.data import DataLoader,random_split
from PIL import Image
import torchvision
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
import torch.nn.functional as F

# Install Kaggle API client
!pip install kaggle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import csv
import torch
import torch.nn as nn
from torch.utils.data import DataLoader,random_split
from PIL import Image
import torchvision
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
import torch.nn.functional as F
import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

# Adjust paths based on the actual downloaded dataset structure
# The dataset typically has a nested structure like:
# <download_path>/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/
train_base = os.path.join(path, "New Plant Diseases Dataset(Augmented)", "New Plant Diseases Dataset(Augmented)")

train_dir = os.path.join(train_base, "train")
valid_dir = os.path.join(train_base, "valid")

# The test directory might be at a different level, often directly under the first 'New Plant Diseases Dataset(Augmented)'
# or directly under the downloaded path. Assuming it's under the first 'New Plant Diseases Dataset(Augmented)'
test_dir = os.path.join(path, "New Plant Diseases Dataset(Augmented)", "test")

Diseases_classes = os.listdir(train_dir)
print(Diseases_classes)
print("\nTotal number of classes are: ", len(Diseases_classes))
plant_names = []
Len = []
for i in Diseases_classes:
    plant_names.append(i)
    imgs_path = os.listdir(train_dir + "/" + i)
    Len.append(len(imgs_path))
Len.sort(reverse=True)
sns.set(style="whitegrid", color_codes=True)
plt.figure(figsize=(20,20),dpi=200)
ax = sns.barplot(x= Len, y= plant_names, palette="Reds_r")
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)
plt.show()
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(
        [0.485, 0.456, 0.406],
        [0.229, 0.224, 0.225]
    )
])
train = ImageFolder(train_dir, transform=transform)
valid = ImageFolder(valid_dir, transform=transform)
val_size = len(valid) // 2
test_size = len(valid) - val_size
val_dataset, test_dataset = random_split(valid, [val_size, test_size])
img, label = train[0]
print(img.shape, label)
train_loader = DataLoader(train, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_dataset,batch_size=16, shuffle=False)

class SimpleCNN(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1),nn.ReLU(),nn.MaxPool2d(2),
            nn.Conv2d(32, 64, 3, padding=1),nn.ReLU(),nn.MaxPool2d(2),
            nn.Conv2d(64, 128, 3, padding=1),nn.ReLU(),
            nn.AdaptiveAvgPool2d((1,1)),
            nn.Flatten(),
            nn.Linear(128, num_classes)
        )
    def forward(self, x):
        return self.net(x)

num_classes=len(train_loader.dataset.classes)
DEVICE="cuda" if torch.cuda.is_available() else "cpu"

def evaluate_classifier(model, loader, device):
    model.eval()

    correct, total = 0, 0
    total_loss = 0

    loss_fn = nn.CrossEntropyLoss()
    with torch.no_grad():
        for x,y in loader:
            x,y=x.to(device),y.to(device)
            out=model(x)
            loss=loss_fn(out, y)
            total_loss+=loss.item()
            preds=out.argmax(1)
            correct+=(preds == y).sum().item()
            total+=y.size(0)
    acc=correct / total
    loss=total_loss/len(loader)
    return loss,acc

def train_classifier(model,loader,device,epochs=5):
    model.train()
    opt=torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn=nn.CrossEntropyLoss()
    for epoch in range(epochs):
        correct,total=0,0
        for i,(x,y) in enumerate(loader):
            x,y=x.to(device),y.to(device)
            out=model(x)
            loss=loss_fn(out,y)
            opt.zero_grad()
            loss.backward()
            opt.step()
            preds=out.argmax(1)
            correct+=(preds == y).sum().item()
            total+=y.size(0)
            if i%100==0:
                print(f"Epoch {epoch+1} | Batch {i+1}/{len(loader)}: Acc={correct/total:.4f}")
        print(f"Classifier Epoch {epoch+1}: Acc={correct/total:.4f}")
    return model

def train_classifier(model, train_loader,val_loader,device,epochs=5):
    model.train()
    opt=torch.optim.Adam(model.parameters(),lr=1e-3)
    loss_fn=nn.CrossEntropyLoss()
    best_val_acc=0
    best_weights=None
    train_accs,val_accs=[],[]
    for epoch in range(epochs):
        model.train()
        correct,total=0, 0
        total_loss=0
        for i,(x, y) in enumerate(train_loader):
            x,y=x.to(device),y.to(device)
            out=model(x)
            loss=loss_fn(out,y)
            opt.zero_grad()
            loss.backward()
            opt.step()
            total_loss+=loss.item()
            preds=out.argmax(1)
            correct+=(preds == y).sum().item()
            total+=y.size(0)
            if i % 100==0:
                print(f"Epoch {epoch+1} | Batch {i+1}/{len(train_loader)} "
                      f"| Train Acc={correct/total:.4f}")
        train_acc=correct/total
        train_accs.append(train_acc)
        val_loss,val_acc=evaluate_classifier(model, val_loader, device)
        val_accs.append(val_acc)
        print(f"\nEpoch {epoch+1}: "
              f"Train Acc={train_acc:.4f} | "
              f"Val Acc={val_acc:.4f}\n")
        if val_acc>best_val_acc:
            best_val_acc=val_acc
            best_weights=model.state_dict()
    return model,best_weights,train_accs,val_accs

model=SimpleCNN(num_classes).to(DEVICE)
model,best_weights, train_accs, val_accs = train_classifier(
    model,
    train_loader,
    val_loader,
    DEVICE,
    epochs=5)

test_loader = DataLoader(
    test_dataset,
    batch_size=16,
    shuffle=False,)
model.load_state_dict(best_weights)
test_loss, test_acc = evaluate_classifier(model, test_loader, DEVICE)
print("Test Accuracy:", test_acc)

